### ISSUE TITLE
1.0.2 on X11

### ISSUE THREAD

**Issue by yFkC1gTR59txdch2dGWT** [flathub/me.hyliu.fluentreader#5]
After updating to 1.0.2 Fluent will no longer launch on X11

`[3 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/fluent-reader/fluent-reader --type=zygote
[3:0629/004845.168400:FATAL:ozone_platform_wayland.cc(173)] Failed to initialize Wayland platform
/app/bin/start-fluent-reader: line 2:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/fluent-reader/fluent-reader --enable-features=UseOzonePlatform --ozone-platform=wayland`

https://github.com/flathub/me.hyliu.fluentreader/commit/de55f6e76d41b79a51df934bf6cf14424bd7a1db?branch=de55f6e76d41b79a51df934bf6cf14424bd7a1db&diff=unified#diff-149b8a2ad4f6ddcc0141e671d36d2390ead73ddf22f00a7507087d8a414efc83R67

Is this by design?
if so is there any override I can do or am I just out of luck until I migrate to wayland?

**Comment by xcffl** [comment]
Can you test if https://github.com/flathub/me.hyliu.fluentreader/pull/6 fixes the issue?

**Comment by yFkC1gTR59txdch2dGWT** [comment]
Works, very much appreciated!
